### ISSUE TITLE
Datepicker not showing in iOS 9

### ISSUE THREAD

**Issue by fpena** [DenHeadless/DTInlineDatePicker#5]
Just for iOS 9, the cell doesn't display correctly the date picker. Only blank space.

<img width="389" alt="captura de pantalla 2015-10-01 a las 11 51 55" src="https://cloud.githubusercontent.com/assets/440097/10224105/de68348a-6832-11e5-9b1e-371f1391ffa9.png">

**Comment by DenHeadless** [comment]
Interesting, i'll try to look at it when i have time, hopefully this weekend.

**Comment by fpena** [comment]
I have a solution.

In the DTInlinePickerCell.m file, replace the `- (void)updateWithModel:(id)model`function with this:

`if ([model isKindOfClass:[DTDatePickerPresenter class]])
    {
        DTDatePickerPresenter * presenter = model;
        self.pickerView = presenter.datePicker;
        [self.contentView addSubview:self.pickerView];
        
        NSLayoutConstraint *topConstraints = [NSLayoutConstraint constraintWithItem:self.contentView attribute:NSLayoutAttributeTop relatedBy:NSLayoutRelationEqual toItem:self.pickerView attribute:NSLayoutAttributeTop multiplier:1 constant:0];
        
        NSLayoutConstraint *bottomConstraints = [NSLayoutConstraint constraintWithItem:self.contentView attribute:NSLayoutAttributeBottom relatedBy:NSLayoutRelationEqual toItem:self.pickerView attribute:NSLayoutAttributeBottom multiplier:1 constant:0];
        
        NSLayoutConstraint *leadingConstraints = [NSLayoutConstraint constraintWithItem:self.contentView attribute:NSLayoutAttributeLeading relatedBy:NSLayoutRelationEqual toItem:self.pickerView attribute:NSLayoutAttributeLeading multiplier:1 constant:0];
        
        NSLayoutConstraint *trailingConstraints = [NSLayoutConstraint constraintWithItem:self.contentView attribute:NSLayoutAttributeTrailing relatedBy:NSLayoutRelationEqual toItem:self.pickerView attribute:NSLayoutAttributeTrailing multiplier:1 constant:0];
        
        self.pickerView.translatesAutoresizingMaskIntoConstraints = NO;
        [self.contentView addConstraints:@[topConstraints, bottomConstraints, leadingConstraints, trailingConstraints]];
    }`

**Comment by DenHeadless** [comment]
Probably that's because of self-sizing cells and UIDatePicker being adaptive on iOS 9. It would be great if you would be able to send pull request with this fix.

**Comment by fpena** [comment]
PR created.
