### ISSUE TITLE
pod doesn't install correctly when using "use_frameworks!"

### ISSUE THREAD

**Issue by aphex3k** [DenHeadless/DTInlineDatePicker#8]
Example PodFile:

```
platform :ios, '9.0'
use_frameworks!
pod 'DTInlineDatePicker', :git => 'https://github.com/DenHeadless/DTInlineDatePicker.git'
```

It produces the following errors:

> Could not build Objective-C module 'DTInlineDatePicker'

and

> 'DTTableViewCell.h' file not found

**Comment by aphex3k** [comment]
if you change DTInlinePickerCell.h line 7 from
`#import "DTTableViewCell.h"`
to
`#import <DTTableViewManager/DTTableViewCell.h>`
it resolves the issues and errors on the next header file...

**Comment by aphex3k** [comment]
in file DTInlinePickerTableController.h change line 9 and 10 to

```
#import <DTTableViewManager/DTTableViewController.h>
#import <DTPickerPresenter/DTDatePickerPresenter.h>
```

and now everything works... 😉

**Comment by DenTelezhkin** [comment]
Can I ask you to drop a PR, that fixes this? I'll made a new release with it then.
